name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: job1
        uses: actions/checkout@v2
      - name: job2
        run: env | sort
    

  job2:
    name: Second job
    runs-on: windows-latests
    steps:
      - name: job1
        uses: actions/checkout@v2
      - name: job2
        run: "Get-ChildItem Env: | Sort-Object Name"
